version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: omnex-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./scripts:/app/scripts
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://omnex:omnex@db:5432/omnex
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - LOG_LEVEL=DEBUG
    depends_on:
      - db
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16-alpine
    container_name: omnex-db
    environment:
      - POSTGRES_USER=omnex
      - POSTGRES_PASSWORD=omnex
      - POSTGRES_DB=omnex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omnex"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: omnex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: omnex-celery-worker
    volumes:
      - ./src:/app/src
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://omnex:omnex@db:5432/omnex
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    command: celery -A src.core.celery worker --loglevel=info

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: omnex-celery-beat
    volumes:
      - ./src:/app/src
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://omnex:omnex@db:5432/omnex
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    command: celery -A src.core.celery beat --loglevel=info

  flower:
    image: mher/flower:2.0
    container_name: omnex-flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - FLOWER_PORT=5555
    depends_on:
      - redis
      - celery-worker

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: mcp
    container_name: omnex-mcp-server
    ports:
      - "3000:3000"
    volumes:
      - ./src/mcp:/app/src/mcp
    environment:
      - MCP_SERVER_PORT=3000
      - DATABASE_URL=postgresql://omnex:omnex@db:5432/omnex
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: python -m src.mcp.server

volumes:
  postgres_data:
  redis_data: