blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/omnex-ai/omnex/discussions
    about: Please ask and answer questions here.
  - name: Security Issues
    url: mailto:security@omnex.ai
    about: Please report security vulnerabilities here.